# Docs for the Azure Web Apps Deploy action: https://github.com/Azure/webapps-deploy
# More GitHub Actions for Azure: https://github.com/Azure/actions

name: Build and deploy Node.js app to Azure Web App - gradguide-backend-jerin

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read #This is required for actions/checkout

    steps:
      - uses: actions/checkout@v4

      - name: Set up Node.js version
        uses: actions/setup-node@v3
        with:
          node-version: '20.x'

      - name: npm install and build backend
        run: |
          cd backend/ # <--- NEW: Navigate into the backend directory
          npm install
          npm run build --if-present
          # No working-directory needed here, as we cd'd
        # Remove working-directory: backend/ from this step if it's there
        # working-directory: backend/ # <--- REMOVE OR COMMENT OUT THIS LINE if it conflicts

      - name: Upload artifact for deployment job
        uses: actions/upload-artifact@v4
        with:
          name: node-app
          path: backend/

  deploy:
    runs-on: ubuntu-latest
    needs: build
    permissions:
      id-token: write #This is required for requesting the JWT
      contents: read #This is required for actions/checkout

    steps:
      - name: Download artifact from build job
        uses: actions/download-artifact@v4
        with:
          name: node-app
          path: . # <--- CRITICAL: Download artifact to current directory (so backend/ is at root)

      - name: Login to Azure
        uses: azure/login@v2
        with:
          # Pass the single JSON credentials secret
          creds: ${{ secrets.AZURE_CREDENTIALS }} # <--- CHANGE THIS LINE

      - name: 'Deploy to Azure Web App'
        id: deploy-to-webapp
        uses: azure/webapps-deploy@v3
        with:
          app-name: 'gradguide-backend-jerin'
          slot-name: 'Production'
          package: . # <--- CHANGE THIS LINE: Deploy the contents of the current directory (which is 'backend/')
